project:
  type: website
  output-dir: docs

website:
  title: "Georgia G. Hernández"
  navbar:
    right:
      - href: index.qmd
        text: About
      - research.qmd
      - publications.qmd
      - href: CVGGH_20250625.pdf
        text: CV
      - href: contact.qmd
  page-footer: 
    left: "Copyright 2025, Georgia G. Hernández"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

